AllCops:
  NewCops: enable
  SuggestExtensions: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*_spec.rb

Layout/LineLength:
  Max: 120

Lint/NestedMethodDefinition:
  Exclude:
    - lib/rspec/its.rb

Lint/SendWithMixinArgument:
  Exclude:
    - lib/rspec/its.rb

Metrics/AbcSize:
  Exclude:
    - lib/rspec/its.rb

Metrics/MethodLength:
  Max: 25

Naming/PredicateName:
  Exclude:
    - lib/rspec/its.rb

Style/CaseEquality:
  Exclude:
    - lib/rspec/its/subject.rb

Style/SignalException:
  Exclude:
    - features/**/*.rb

Style/SpecialGlobalVars:
  Exclude:
    - rspec-its.gemspec

# We don't care about single vs double quotes.
Style/StringLiterals:
  Enabled: false
